version: "2"

services:
  service1:
    build: ./service1
    restart: always
    ports: 
    - 8081:8081

  service2:
    build: ./service2
    restart: always
    ports: 
    - 8082:8082

  service3:
    build: ./service3
    restart: always
    ports: 
    - 8083:8083

  proxy:
    build: ./redbird-proxy
    restart: always
    ports:
    - 80:80
    links:
    - service1:service1
    - service2:service2
    - service3:service3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
